package com.ik.crm.fix.tools.service.cust.impl;

import com.ik.crm.fix.tools.mapper.cust.CustomersMapper;
import com.ik.crm.fix.tools.model.cust.Customers;
import com.ik.crm.fix.tools.service.cust.CustomersService;
import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: CustomersServiceImpl
* Mapper : CustomersMapper
* Model  : Customers
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-10-30 18:17:13
*/
@Service
@Transactional
public class CustomersServiceImpl extends GenericServiceImpl<Customers, Integer, CustomersMapper> implements CustomersService {
    @Autowired
    private CustomersMapper customersMapper;

    @Override
    public CustomersMapper getGenericMapper() {
        return customersMapper;
    }
}