package com.ik.crm.fix.tools.model.cust;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
* Model: Customers
* Table: customers
* Alias: cust
*
* This Model generated by MyBatis Generator Extend.
*/
public class Customers extends BaseModel<Integer> implements Serializable {
    /**
     * 
     * name
     */
    private String name;

    /**
     * 
     * category
     */
    private String category;

    /**
     * 
     * source
     */
    private String source;

    /**
     * 
     * industry
     */
    private String industry;

    /**
     * 
     * staff_size
     */
    private String staff_size;

    /**
     * 
     * created_at
     */
    private Date created_at;

    /**
     * 
     * updated_at
     */
    private Date updated_at;

    /**
     * 
     * organization_id
     */
    private Integer organization_id;

    /**
     * 
     * user_id
     */
    private Integer user_id;

    /**
     * 
     * parent_id
     */
    private Integer parent_id;

    /**
     * 
     * path
     */
    private String path;

    /**
     * 
     * status
     */
    private String status;

    /**
     * 
     * status_locked
     */
    private Boolean status_locked;

    /**
     * 
     * department_id
     */
    private Integer department_id;

    /**
     * 
     * name_pinyin
     */
    private String name_pinyin;

    /**
     * 
     * revisit_at
     */
    private Date revisit_at;

    /**
     * 
     * real_revisit_at
     */
    private Date real_revisit_at;

    /**
     * 
     * revisit_remind_at
     */
    private Date revisit_remind_at;

    /**
     * 
     * company_name
     */
    private String company_name;

    /**
     * 
     * qixinbao_id
     */
    private String qixinbao_id;

    /**
     * 
     * creator_id
     */
    private Integer creator_id;

    /**
     * 
     * before_user_id
     */
    private Integer before_user_id;

    /**
     * 
     * before_department_id
     */
    private Integer before_department_id;

    /**
     * 
     * flow_into_at
     */
    private Date flow_into_at;

    /**
     * 
     * status_updated_at
     */
    private Date status_updated_at;

    /**
     * 
     * customer_common_setting_id
     */
    private Integer customer_common_setting_id;

    /**
     * 
     * before_customer_common_setting_id
     */
    private Integer before_customer_common_setting_id;

    /**
     * 
     * approve_status
     */
    private Byte approve_status;

    /**
     * 
     * approve_deny_type
     */
    private Byte approve_deny_type;

    /**
     * 
     * step
     */
    private Integer step;

    /**
     * 
     * submit_applying_at
     */
    private Date submit_applying_at;

    /**
     * 
     * finish_approve_at
     */
    private Date finish_approve_at;

    /**
     * 
     * pending_step
     */
    private Integer pending_step;

    /**
     * 
     * industry_category
     */
    private Integer industry_category;

    /**
     * 
     * note
     */
    private String note;

    private static final long serialVersionUID = 1L;

    /**
     * 
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * name
     *
     * @param name 
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     * category
     */
    public String getCategory() {
        return category;
    }

    /**
     * 
     * category
     *
     * @param category 
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * 
     * source
     */
    public String getSource() {
        return source;
    }

    /**
     * 
     * source
     *
     * @param source 
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * 
     * industry
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * 
     * industry
     *
     * @param industry 
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * 
     * staff_size
     */
    public String getStaff_size() {
        return staff_size;
    }

    /**
     * 
     * staff_size
     *
     * @param staff_size 
     */
    public void setStaff_size(String staff_size) {
        this.staff_size = staff_size;
    }

    /**
     * 
     * created_at
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * 
     * created_at
     *
     * @param created_at 
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * 
     * updated_at
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * 
     * updated_at
     *
     * @param updated_at 
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * 
     * organization_id
     */
    public Integer getOrganization_id() {
        return organization_id;
    }

    /**
     * 
     * organization_id
     *
     * @param organization_id 
     */
    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    /**
     * 
     * user_id
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * 
     * user_id
     *
     * @param user_id 
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * 
     * parent_id
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * 
     * parent_id
     *
     * @param parent_id 
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * 
     * path
     */
    public String getPath() {
        return path;
    }

    /**
     * 
     * path
     *
     * @param path 
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * 
     * status
     */
    public String getStatus() {
        return status;
    }

    /**
     * 
     * status
     *
     * @param status 
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 
     * status_locked
     */
    public Boolean getStatus_locked() {
        return status_locked;
    }

    /**
     * 
     * status_locked
     *
     * @param status_locked 
     */
    public void setStatus_locked(Boolean status_locked) {
        this.status_locked = status_locked;
    }

    /**
     * 
     * department_id
     */
    public Integer getDepartment_id() {
        return department_id;
    }

    /**
     * 
     * department_id
     *
     * @param department_id 
     */
    public void setDepartment_id(Integer department_id) {
        this.department_id = department_id;
    }

    /**
     * 
     * name_pinyin
     */
    public String getName_pinyin() {
        return name_pinyin;
    }

    /**
     * 
     * name_pinyin
     *
     * @param name_pinyin 
     */
    public void setName_pinyin(String name_pinyin) {
        this.name_pinyin = name_pinyin;
    }

    /**
     * 
     * revisit_at
     */
    public Date getRevisit_at() {
        return revisit_at;
    }

    /**
     * 
     * revisit_at
     *
     * @param revisit_at 
     */
    public void setRevisit_at(Date revisit_at) {
        this.revisit_at = revisit_at;
    }

    /**
     * 
     * real_revisit_at
     */
    public Date getReal_revisit_at() {
        return real_revisit_at;
    }

    /**
     * 
     * real_revisit_at
     *
     * @param real_revisit_at 
     */
    public void setReal_revisit_at(Date real_revisit_at) {
        this.real_revisit_at = real_revisit_at;
    }

    /**
     * 
     * revisit_remind_at
     */
    public Date getRevisit_remind_at() {
        return revisit_remind_at;
    }

    /**
     * 
     * revisit_remind_at
     *
     * @param revisit_remind_at 
     */
    public void setRevisit_remind_at(Date revisit_remind_at) {
        this.revisit_remind_at = revisit_remind_at;
    }

    /**
     * 
     * company_name
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * 
     * company_name
     *
     * @param company_name 
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    /**
     * 
     * qixinbao_id
     */
    public String getQixinbao_id() {
        return qixinbao_id;
    }

    /**
     * 
     * qixinbao_id
     *
     * @param qixinbao_id 
     */
    public void setQixinbao_id(String qixinbao_id) {
        this.qixinbao_id = qixinbao_id;
    }

    /**
     * 
     * creator_id
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * 
     * creator_id
     *
     * @param creator_id 
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * 
     * before_user_id
     */
    public Integer getBefore_user_id() {
        return before_user_id;
    }

    /**
     * 
     * before_user_id
     *
     * @param before_user_id 
     */
    public void setBefore_user_id(Integer before_user_id) {
        this.before_user_id = before_user_id;
    }

    /**
     * 
     * before_department_id
     */
    public Integer getBefore_department_id() {
        return before_department_id;
    }

    /**
     * 
     * before_department_id
     *
     * @param before_department_id 
     */
    public void setBefore_department_id(Integer before_department_id) {
        this.before_department_id = before_department_id;
    }

    /**
     * 
     * flow_into_at
     */
    public Date getFlow_into_at() {
        return flow_into_at;
    }

    /**
     * 
     * flow_into_at
     *
     * @param flow_into_at 
     */
    public void setFlow_into_at(Date flow_into_at) {
        this.flow_into_at = flow_into_at;
    }

    /**
     * 
     * status_updated_at
     */
    public Date getStatus_updated_at() {
        return status_updated_at;
    }

    /**
     * 
     * status_updated_at
     *
     * @param status_updated_at 
     */
    public void setStatus_updated_at(Date status_updated_at) {
        this.status_updated_at = status_updated_at;
    }

    /**
     * 
     * customer_common_setting_id
     */
    public Integer getCustomer_common_setting_id() {
        return customer_common_setting_id;
    }

    /**
     * 
     * customer_common_setting_id
     *
     * @param customer_common_setting_id 
     */
    public void setCustomer_common_setting_id(Integer customer_common_setting_id) {
        this.customer_common_setting_id = customer_common_setting_id;
    }

    /**
     * 
     * before_customer_common_setting_id
     */
    public Integer getBefore_customer_common_setting_id() {
        return before_customer_common_setting_id;
    }

    /**
     * 
     * before_customer_common_setting_id
     *
     * @param before_customer_common_setting_id 
     */
    public void setBefore_customer_common_setting_id(Integer before_customer_common_setting_id) {
        this.before_customer_common_setting_id = before_customer_common_setting_id;
    }

    /**
     * 
     * approve_status
     */
    public Byte getApprove_status() {
        return approve_status;
    }

    /**
     * 
     * approve_status
     *
     * @param approve_status 
     */
    public void setApprove_status(Byte approve_status) {
        this.approve_status = approve_status;
    }

    /**
     * 
     * approve_deny_type
     */
    public Byte getApprove_deny_type() {
        return approve_deny_type;
    }

    /**
     * 
     * approve_deny_type
     *
     * @param approve_deny_type 
     */
    public void setApprove_deny_type(Byte approve_deny_type) {
        this.approve_deny_type = approve_deny_type;
    }

    /**
     * 
     * step
     */
    public Integer getStep() {
        return step;
    }

    /**
     * 
     * step
     *
     * @param step 
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * 
     * submit_applying_at
     */
    public Date getSubmit_applying_at() {
        return submit_applying_at;
    }

    /**
     * 
     * submit_applying_at
     *
     * @param submit_applying_at 
     */
    public void setSubmit_applying_at(Date submit_applying_at) {
        this.submit_applying_at = submit_applying_at;
    }

    /**
     * 
     * finish_approve_at
     */
    public Date getFinish_approve_at() {
        return finish_approve_at;
    }

    /**
     * 
     * finish_approve_at
     *
     * @param finish_approve_at 
     */
    public void setFinish_approve_at(Date finish_approve_at) {
        this.finish_approve_at = finish_approve_at;
    }

    /**
     * 
     * pending_step
     */
    public Integer getPending_step() {
        return pending_step;
    }

    /**
     * 
     * pending_step
     *
     * @param pending_step 
     */
    public void setPending_step(Integer pending_step) {
        this.pending_step = pending_step;
    }

    /**
     * 
     * industry_category
     */
    public Integer getIndustry_category() {
        return industry_category;
    }

    /**
     * 
     * industry_category
     *
     * @param industry_category 
     */
    public void setIndustry_category(Integer industry_category) {
        this.industry_category = industry_category;
    }

    /**
     * 
     * note
     */
    public String getNote() {
        return note;
    }

    /**
     * 
     * note
     *
     * @param note 
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", category=").append(category);
        sb.append(", source=").append(source);
        sb.append(", industry=").append(industry);
        sb.append(", staff_size=").append(staff_size);
        sb.append(", created_at=").append(created_at);
        sb.append(", updated_at=").append(updated_at);
        sb.append(", organization_id=").append(organization_id);
        sb.append(", user_id=").append(user_id);
        sb.append(", parent_id=").append(parent_id);
        sb.append(", path=").append(path);
        sb.append(", status=").append(status);
        sb.append(", status_locked=").append(status_locked);
        sb.append(", department_id=").append(department_id);
        sb.append(", name_pinyin=").append(name_pinyin);
        sb.append(", revisit_at=").append(revisit_at);
        sb.append(", real_revisit_at=").append(real_revisit_at);
        sb.append(", revisit_remind_at=").append(revisit_remind_at);
        sb.append(", company_name=").append(company_name);
        sb.append(", qixinbao_id=").append(qixinbao_id);
        sb.append(", creator_id=").append(creator_id);
        sb.append(", before_user_id=").append(before_user_id);
        sb.append(", before_department_id=").append(before_department_id);
        sb.append(", flow_into_at=").append(flow_into_at);
        sb.append(", status_updated_at=").append(status_updated_at);
        sb.append(", customer_common_setting_id=").append(customer_common_setting_id);
        sb.append(", before_customer_common_setting_id=").append(before_customer_common_setting_id);
        sb.append(", approve_status=").append(approve_status);
        sb.append(", approve_deny_type=").append(approve_deny_type);
        sb.append(", step=").append(step);
        sb.append(", submit_applying_at=").append(submit_applying_at);
        sb.append(", finish_approve_at=").append(finish_approve_at);
        sb.append(", pending_step=").append(pending_step);
        sb.append(", industry_category=").append(industry_category);
        sb.append(", note=").append(note);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customers other = (Customers) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}