package com.ik.crm.fix.tools.mapper;

import com.ik.crm.fix.tools.model.ContactAddresses;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
* Mapper: ContactAddressesMapper
* Model : ContactAddresses
* Table : contact_addresses
*
* This Mapper generated by MyBatis Generator Extend at 2017-10-26 18:07:23
*/
public interface ContactAddressesMapper extends GenericMapper<ContactAddresses, Integer> {
}