package com.ik.crm.fix.tools.mapper;

import com.ik.crm.fix.tools.model.ContactAssets;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
* Mapper: ContactAssetsMapper
* Model : ContactAssets
* Table : contact_assets
*
* This Mapper generated by MyBatis Generator Extend at 2017-10-26 18:07:23
*/
public interface ContactAssetsMapper extends GenericMapper<ContactAssets, Integer> {
}