package com.ik.crm.fix.tools.mapper;

import com.ik.crm.fix.tools.model.Contacts;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
* Mapper: ContactsMapper
* Model : Contacts
* Table : contacts
*
* This Mapper generated by MyBatis Generator Extend at 2017-10-26 18:07:23
*/
public interface ContactsMapper extends GenericMapper<Contacts, Integer> {


    @Select("select id from contacts where customer_id = #{custId} and organization_id = #{orgId} and (created_at between '2017-10-24 11:54:42' and '2017-10-25 02:55:50') and created_at = updated_at limit 1")
    Integer getContactsId(@Param("custId") Integer custId, @Param("orgId") Integer orgId);

}