package com.ik.crm.fix.tools.mapper;

import com.ik.crm.fix.tools.model.CustomerAssets;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mybatis.extend.generic.mapper.GenericMapper;

import java.util.List;

/**
* Mapper: CustomerAssetsMapper
* Model : CustomerAssets
* Table : customer_assets
*
* This Mapper generated by MyBatis Generator Extend at 2017-10-26 18:07:23
*/
public interface CustomerAssetsMapper extends GenericMapper<CustomerAssets, Integer> {

    @Select("select id from customer_assets where entity_id = #{custId} and organization_id = #{orgId} and (created_at between '2017-10-24 11:54:42' and '2017-10-25 02:55:50') and created_at = updated_at")
    List<Integer> getCustomerAssetsList(@Param("custId") Integer custId, @Param("orgId") Integer orgId);
}