package com.ik.crm.fix.tools.mapper.cust;

import com.ik.crm.fix.tools.model.cust.Customers;
import org.mybatis.extend.generic.mapper.GenericMapper;

import java.util.List;

/**
* Mapper: CustomersMapper
* Model : Customers
* Table : customers
*
* This Mapper generated by MyBatis Generator Extend at 2017-10-30 18:17:13
*/
public interface CustomersMapper extends GenericMapper<Customers, Integer> {

    void batchInsertSelective(List<Customers> customersList);

}