package com.ik.crm.fix.tools.service.cust;

import com.ik.crm.fix.tools.model.cust.Customers;
import org.mybatis.extend.generic.service.GenericService;

/**
* Service: CustomersService
* Mapper : CustomersMapper
* Model  : Customers
*
* This Service generated by MyBatis Generator Extend at 2017-10-30 18:17:13
*/
public interface CustomersService extends GenericService<Customers, Integer> {
}