package com.ik.crm.fix.tools.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
* Model: ContactAssets
* Table: contact_assets
* Alias: null
*
* This Model generated by MyBatis Generator Extend.
*/
public class ContactAssets extends BaseModel<Integer> implements Serializable {
    /**
     * 
     * text_asset
     */
    private String text_asset;

    /**
     * 
     * date_asset
     */
    private Date date_asset;

    /**
     * 
     * datetime_asset
     */
    private Date datetime_asset;

    /**
     * 
     * numeric_asset
     */
    private BigDecimal numeric_asset;

    /**
     * 
     * entity_id
     */
    private Integer entity_id;

    /**
     * 
     * custom_field_name
     */
    private String custom_field_name;

    /**
     * 
     * custom_field_id
     */
    private Integer custom_field_id;

    /**
     * 
     * organization_id
     */
    private Integer organization_id;

    /**
     * 
     * created_at
     */
    private Date created_at;

    /**
     * 
     * updated_at
     */
    private Date updated_at;

    /**
     * 
     * text_area_asset
     */
    private String text_area_asset;

    private static final long serialVersionUID = 1L;

    /**
     * 
     * text_asset
     */
    public String getText_asset() {
        return text_asset;
    }

    /**
     * 
     * text_asset
     *
     * @param text_asset 
     */
    public void setText_asset(String text_asset) {
        this.text_asset = text_asset;
    }

    /**
     * 
     * date_asset
     */
    public Date getDate_asset() {
        return date_asset;
    }

    /**
     * 
     * date_asset
     *
     * @param date_asset 
     */
    public void setDate_asset(Date date_asset) {
        this.date_asset = date_asset;
    }

    /**
     * 
     * datetime_asset
     */
    public Date getDatetime_asset() {
        return datetime_asset;
    }

    /**
     * 
     * datetime_asset
     *
     * @param datetime_asset 
     */
    public void setDatetime_asset(Date datetime_asset) {
        this.datetime_asset = datetime_asset;
    }

    /**
     * 
     * numeric_asset
     */
    public BigDecimal getNumeric_asset() {
        return numeric_asset;
    }

    /**
     * 
     * numeric_asset
     *
     * @param numeric_asset 
     */
    public void setNumeric_asset(BigDecimal numeric_asset) {
        this.numeric_asset = numeric_asset;
    }

    /**
     * 
     * entity_id
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * 
     * entity_id
     *
     * @param entity_id 
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * 
     * custom_field_name
     */
    public String getCustom_field_name() {
        return custom_field_name;
    }

    /**
     * 
     * custom_field_name
     *
     * @param custom_field_name 
     */
    public void setCustom_field_name(String custom_field_name) {
        this.custom_field_name = custom_field_name;
    }

    /**
     * 
     * custom_field_id
     */
    public Integer getCustom_field_id() {
        return custom_field_id;
    }

    /**
     * 
     * custom_field_id
     *
     * @param custom_field_id 
     */
    public void setCustom_field_id(Integer custom_field_id) {
        this.custom_field_id = custom_field_id;
    }

    /**
     * 
     * organization_id
     */
    public Integer getOrganization_id() {
        return organization_id;
    }

    /**
     * 
     * organization_id
     *
     * @param organization_id 
     */
    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    /**
     * 
     * created_at
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * 
     * created_at
     *
     * @param created_at 
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * 
     * updated_at
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * 
     * updated_at
     *
     * @param updated_at 
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * 
     * text_area_asset
     */
    public String getText_area_asset() {
        return text_area_asset;
    }

    /**
     * 
     * text_area_asset
     *
     * @param text_area_asset 
     */
    public void setText_area_asset(String text_area_asset) {
        this.text_area_asset = text_area_asset;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", text_asset=").append(text_asset);
        sb.append(", date_asset=").append(date_asset);
        sb.append(", datetime_asset=").append(datetime_asset);
        sb.append(", numeric_asset=").append(numeric_asset);
        sb.append(", entity_id=").append(entity_id);
        sb.append(", custom_field_name=").append(custom_field_name);
        sb.append(", custom_field_id=").append(custom_field_id);
        sb.append(", organization_id=").append(organization_id);
        sb.append(", created_at=").append(created_at);
        sb.append(", updated_at=").append(updated_at);
        sb.append(", text_area_asset=").append(text_area_asset);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContactAssets other = (ContactAssets) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}