package com.ik.crm.fix.tools.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
* Model: Contacts
* Table: contacts
* Alias: null
*
* This Model generated by MyBatis Generator Extend.
*/
public class Contacts extends BaseModel<Integer> implements Serializable {
    /**
     * 
     * name
     */
    private String name;

    /**
     * 
     * user_id
     */
    private Integer user_id;

    /**
     * 
     * department
     */
    private String department;

    /**
     * 
     * job
     */
    private String job;

    /**
     * 
     * created_at
     */
    private Date created_at;

    /**
     * 
     * updated_at
     */
    private Date updated_at;

    /**
     * 
     * organization_id
     */
    private Integer organization_id;

    /**
     * 
     * parent_id
     */
    private Integer parent_id;

    /**
     * 
     * gender
     */
    private Integer gender;

    /**
     * 
     * category
     */
    private String category;

    /**
     * 
     * customer_id
     */
    private Integer customer_id;

    /**
     * 
     * birth_date
     */
    private Date birth_date;

    /**
     * 
     * name_pinyin
     */
    private String name_pinyin;

    /**
     * 
     * born_from
     */
    private Integer born_from;

    /**
     * 
     * creator_id
     */
    private Integer creator_id;

    /**
     * 
     * before_user_id
     */
    private Integer before_user_id;

    /**
     * 
     * ding_ext_contact_id
     */
    private String ding_ext_contact_id;

    /**
     * 
     * note
     */
    private String note;

    private static final long serialVersionUID = 1L;

    /**
     * 
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * name
     *
     * @param name 
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     * user_id
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * 
     * user_id
     *
     * @param user_id 
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * 
     * department
     */
    public String getDepartment() {
        return department;
    }

    /**
     * 
     * department
     *
     * @param department 
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * 
     * job
     */
    public String getJob() {
        return job;
    }

    /**
     * 
     * job
     *
     * @param job 
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * 
     * created_at
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * 
     * created_at
     *
     * @param created_at 
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * 
     * updated_at
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * 
     * updated_at
     *
     * @param updated_at 
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * 
     * organization_id
     */
    public Integer getOrganization_id() {
        return organization_id;
    }

    /**
     * 
     * organization_id
     *
     * @param organization_id 
     */
    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    /**
     * 
     * parent_id
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * 
     * parent_id
     *
     * @param parent_id 
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * 
     * gender
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * 
     * gender
     *
     * @param gender 
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * 
     * category
     */
    public String getCategory() {
        return category;
    }

    /**
     * 
     * category
     *
     * @param category 
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * 
     * customer_id
     */
    public Integer getCustomer_id() {
        return customer_id;
    }

    /**
     * 
     * customer_id
     *
     * @param customer_id 
     */
    public void setCustomer_id(Integer customer_id) {
        this.customer_id = customer_id;
    }

    /**
     * 
     * birth_date
     */
    public Date getBirth_date() {
        return birth_date;
    }

    /**
     * 
     * birth_date
     *
     * @param birth_date 
     */
    public void setBirth_date(Date birth_date) {
        this.birth_date = birth_date;
    }

    /**
     * 
     * name_pinyin
     */
    public String getName_pinyin() {
        return name_pinyin;
    }

    /**
     * 
     * name_pinyin
     *
     * @param name_pinyin 
     */
    public void setName_pinyin(String name_pinyin) {
        this.name_pinyin = name_pinyin;
    }

    /**
     * 
     * born_from
     */
    public Integer getBorn_from() {
        return born_from;
    }

    /**
     * 
     * born_from
     *
     * @param born_from 
     */
    public void setBorn_from(Integer born_from) {
        this.born_from = born_from;
    }

    /**
     * 
     * creator_id
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * 
     * creator_id
     *
     * @param creator_id 
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * 
     * before_user_id
     */
    public Integer getBefore_user_id() {
        return before_user_id;
    }

    /**
     * 
     * before_user_id
     *
     * @param before_user_id 
     */
    public void setBefore_user_id(Integer before_user_id) {
        this.before_user_id = before_user_id;
    }

    /**
     * 
     * ding_ext_contact_id
     */
    public String getDing_ext_contact_id() {
        return ding_ext_contact_id;
    }

    /**
     * 
     * ding_ext_contact_id
     *
     * @param ding_ext_contact_id 
     */
    public void setDing_ext_contact_id(String ding_ext_contact_id) {
        this.ding_ext_contact_id = ding_ext_contact_id;
    }

    /**
     * 
     * note
     */
    public String getNote() {
        return note;
    }

    /**
     * 
     * note
     *
     * @param note 
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", user_id=").append(user_id);
        sb.append(", department=").append(department);
        sb.append(", job=").append(job);
        sb.append(", created_at=").append(created_at);
        sb.append(", updated_at=").append(updated_at);
        sb.append(", organization_id=").append(organization_id);
        sb.append(", parent_id=").append(parent_id);
        sb.append(", gender=").append(gender);
        sb.append(", category=").append(category);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", birth_date=").append(birth_date);
        sb.append(", name_pinyin=").append(name_pinyin);
        sb.append(", born_from=").append(born_from);
        sb.append(", creator_id=").append(creator_id);
        sb.append(", before_user_id=").append(before_user_id);
        sb.append(", ding_ext_contact_id=").append(ding_ext_contact_id);
        sb.append(", note=").append(note);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Contacts other = (Contacts) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}