package com.ik.crm.fix.tools.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
* Model: ContactAddresses
* Table: contact_addresses
* Alias: null
*
* This Model generated by MyBatis Generator Extend.
*/
public class ContactAddresses extends BaseModel<Integer> implements Serializable {
    /**
     * 
     * addressable_id
     */
    private Integer addressable_id;

    /**
     * 
     * addressable_type
     */
    private String addressable_type;

    /**
     * 
     * country_id
     */
    private Integer country_id;

    /**
     * 
     * province_id
     */
    private Integer province_id;

    /**
     * 
     * city_id
     */
    private Integer city_id;

    /**
     * 
     * district_id
     */
    private Integer district_id;

    /**
     * 
     * tel
     */
    private String tel;

    /**
     * 
     * phone
     */
    private String phone;

    /**
     * 
     * email
     */
    private String email;

    /**
     * 
     * qq
     */
    private String qq;

    /**
     * 
     * fax
     */
    private String fax;

    /**
     * 
     * wechat
     */
    private String wechat;

    /**
     * 
     * wangwang
     */
    private String wangwang;

    /**
     * 
     * zip
     */
    private String zip;

    /**
     * 
     * url
     */
    private String url;

    /**
     * 
     * detail_address
     */
    private String detail_address;

    /**
     * 
     * created_at
     */
    private Date created_at;

    /**
     * 
     * updated_at
     */
    private Date updated_at;

    /**
     * 
     * lat
     */
    private BigDecimal lat;

    /**
     * 
     * lng
     */
    private BigDecimal lng;

    /**
     * 
     * off_distance
     */
    private Float off_distance;

    /**
     * 
     * region_info
     */
    private String region_info;

    /**
     * 
     * snippet
     */
    private String snippet;

    /**
     * 
     * organization_id
     */
    private Integer organization_id;

    private static final long serialVersionUID = 1L;

    /**
     * 
     * addressable_id
     */
    public Integer getAddressable_id() {
        return addressable_id;
    }

    /**
     * 
     * addressable_id
     *
     * @param addressable_id 
     */
    public void setAddressable_id(Integer addressable_id) {
        this.addressable_id = addressable_id;
    }

    /**
     * 
     * addressable_type
     */
    public String getAddressable_type() {
        return addressable_type;
    }

    /**
     * 
     * addressable_type
     *
     * @param addressable_type 
     */
    public void setAddressable_type(String addressable_type) {
        this.addressable_type = addressable_type;
    }

    /**
     * 
     * country_id
     */
    public Integer getCountry_id() {
        return country_id;
    }

    /**
     * 
     * country_id
     *
     * @param country_id 
     */
    public void setCountry_id(Integer country_id) {
        this.country_id = country_id;
    }

    /**
     * 
     * province_id
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * 
     * province_id
     *
     * @param province_id 
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * 
     * city_id
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * 
     * city_id
     *
     * @param city_id 
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * 
     * district_id
     */
    public Integer getDistrict_id() {
        return district_id;
    }

    /**
     * 
     * district_id
     *
     * @param district_id 
     */
    public void setDistrict_id(Integer district_id) {
        this.district_id = district_id;
    }

    /**
     * 
     * tel
     */
    public String getTel() {
        return tel;
    }

    /**
     * 
     * tel
     *
     * @param tel 
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * 
     * phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 
     * phone
     *
     * @param phone 
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 
     * email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 
     * email
     *
     * @param email 
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 
     * qq
     */
    public String getQq() {
        return qq;
    }

    /**
     * 
     * qq
     *
     * @param qq 
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * 
     * fax
     */
    public String getFax() {
        return fax;
    }

    /**
     * 
     * fax
     *
     * @param fax 
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * 
     * wechat
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * 
     * wechat
     *
     * @param wechat 
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * 
     * wangwang
     */
    public String getWangwang() {
        return wangwang;
    }

    /**
     * 
     * wangwang
     *
     * @param wangwang 
     */
    public void setWangwang(String wangwang) {
        this.wangwang = wangwang;
    }

    /**
     * 
     * zip
     */
    public String getZip() {
        return zip;
    }

    /**
     * 
     * zip
     *
     * @param zip 
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * 
     * url
     */
    public String getUrl() {
        return url;
    }

    /**
     * 
     * url
     *
     * @param url 
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 
     * detail_address
     */
    public String getDetail_address() {
        return detail_address;
    }

    /**
     * 
     * detail_address
     *
     * @param detail_address 
     */
    public void setDetail_address(String detail_address) {
        this.detail_address = detail_address;
    }

    /**
     * 
     * created_at
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * 
     * created_at
     *
     * @param created_at 
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * 
     * updated_at
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * 
     * updated_at
     *
     * @param updated_at 
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * 
     * lat
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * 
     * lat
     *
     * @param lat 
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * 
     * lng
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * 
     * lng
     *
     * @param lng 
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * 
     * off_distance
     */
    public Float getOff_distance() {
        return off_distance;
    }

    /**
     * 
     * off_distance
     *
     * @param off_distance 
     */
    public void setOff_distance(Float off_distance) {
        this.off_distance = off_distance;
    }

    /**
     * 
     * region_info
     */
    public String getRegion_info() {
        return region_info;
    }

    /**
     * 
     * region_info
     *
     * @param region_info 
     */
    public void setRegion_info(String region_info) {
        this.region_info = region_info;
    }

    /**
     * 
     * snippet
     */
    public String getSnippet() {
        return snippet;
    }

    /**
     * 
     * snippet
     *
     * @param snippet 
     */
    public void setSnippet(String snippet) {
        this.snippet = snippet;
    }

    /**
     * 
     * organization_id
     */
    public Integer getOrganization_id() {
        return organization_id;
    }

    /**
     * 
     * organization_id
     *
     * @param organization_id 
     */
    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", addressable_id=").append(addressable_id);
        sb.append(", addressable_type=").append(addressable_type);
        sb.append(", country_id=").append(country_id);
        sb.append(", province_id=").append(province_id);
        sb.append(", city_id=").append(city_id);
        sb.append(", district_id=").append(district_id);
        sb.append(", tel=").append(tel);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", qq=").append(qq);
        sb.append(", fax=").append(fax);
        sb.append(", wechat=").append(wechat);
        sb.append(", wangwang=").append(wangwang);
        sb.append(", zip=").append(zip);
        sb.append(", url=").append(url);
        sb.append(", detail_address=").append(detail_address);
        sb.append(", created_at=").append(created_at);
        sb.append(", updated_at=").append(updated_at);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", off_distance=").append(off_distance);
        sb.append(", region_info=").append(region_info);
        sb.append(", snippet=").append(snippet);
        sb.append(", organization_id=").append(organization_id);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContactAddresses other = (ContactAddresses) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}